# i2s
CONFIG_I2S=y

# serial console logs
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# thread stakcs
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_HEAP_MEM_POOL_SIZE=0

# buttons
CONFIG_GPIO=y
CONFIG_DK_LIBRARY=y

# bluetooth
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_NUS=y
CONFIG_BT_DEVICE_NAME="Beamformer"
CONFIG_BT_MAX_CONN=1
CONFIG_BT_L2CAP_TX_MTU=247
CONFIG_BT_BUF_ACL_TX_SIZE=251
CONFIG_BT_BUF_ACL_TX_COUNT=4
CONFIG_BT_BUF_ACL_RX_SIZE=251

# nRF Edge AI wakeword
CONFIG_NRF_EDGEAI=y
CONFIG_NRF_AXON=y
CONFIG_NEWLIB_LIBC=y
CONFIG_FPU=y
CONFIG_NRF_AXON_INTERLAYER_BUFFER_SIZE=7000
CONFIG_NRF_AXON_PSUM_BUFFER_SIZE=0

CONFIG_WW_PROBABILITY_THRESHOLD=700
CONFIG_WW_HISTORY_SIZE=6
CONFIG_WW_COUNT_THRESHOLD=4

CONFIG_NRF_SYS_EVENT=y
# VAD endpoint tuning
CONFIG_APP_VAD_SILENCE_END_MS=600
