# nRF Edge AI
CONFIG_NRF_EDGEAI=y
# nRF Edge AI dependencies
CONFIG_NEWLIB_LIBC=y
CONFIG_FPU=y
# nRF Axon
CONFIG_NRF_AXON=y
CONFIG_NRF_AXON_INTERLAYER_BUFFER_SIZE=7000
CONFIG_NRF_AXON_PSUM_BUFFER_SIZE=0